# Generated by Django 6.0.1 on 2026-01-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_identity_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_identity_verified',
            new_name='isIdentityVerified',
        ),
    ]
