# Generated by Django 6.0.1 on 2026-01-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_identity_verified_user_isidentityverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verifiedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
