# Generated by Django 6.0.1 on 2026-01-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_verifiedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_account_pin',
            field=models.BooleanField(default=False),
        ),
    ]
