# Generated by Django 6.0.1 on 2026-01-22 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_transaction_pin'),
        migrations.swappable_dependency(settings.FCM_DJANGO_FCMDEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fcm_device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FCM_DJANGO_FCMDEVICE_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
