# Generated by Django 6.0.1 on 2026-02-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_deviceprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaccount',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('crypto', 'Crypto Wallet')], default='bank', max_length=10),
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
