# Generated by Django 6.0.1 on 2026-02-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_currency_preference_user_hide_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
