# Generated by Django 6.0.1 on 2026-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_identity_id_user_verification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='platform',
            field=models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], default='android', max_length=20),
        ),
    ]
