# Generated by Django 6.0.1 on 2026-03-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_deviceprofile_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='android', max_length=20),
        ),
    ]
