# Generated by Django 6.0.1 on 2026-03-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_deviceprofile_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='virtual_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='virtual_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
