# Generated by Django 6.0.1 on 2026-03-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_paystack_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='virtual_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
