# Generated by Django 6.0.1 on 2026-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('raw_body', models.TextField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=64, null=True)),
                ('resource', models.CharField(blank=True, max_length=512, null=True)),
                ('flow_id', models.CharField(blank=True, max_length=64, null=True)),
                ('identity_status', models.CharField(blank=True, max_length=64, null=True)),
                ('verification_id', models.CharField(blank=True, max_length=255, null=True)),
                ('identity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='identity_verification_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('error', 'Error')], default='unverified', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_verification_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
