# Generated by Django 6.0.1 on 2026-03-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_identitywebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaccount',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
