# Generated by Django 6.0.1 on 2026-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0003_alter_agreement_buyer_alter_agreement_counterparty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_acceptance', 'Awaiting Acceptance'), ('terms_locked', 'Terms Locked'), ('active', 'Active'), ('secured', 'Secured'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
