# Generated by Django 6.0.1 on 2026-01-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0004_alter_agreement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='active_offer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_agreement', to='agreement.agreementoffer'),
        ),
        migrations.AlterField(
            model_name='agreementoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('accepted_by_seller', 'Accepted by Seller'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
