# Generated by Django 6.0.1 on 2026-02-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0005_agreement_active_offer_alter_agreementoffer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='amount_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreementoffer',
            name='amount_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreementoffer',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
