# Generated by Django 6.0.1 on 2026-02-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0006_agreement_currency_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_acceptance', 'Awaiting Acceptance'), ('terms_locked', 'Terms Locked'), ('active', 'Active'), ('secured', 'Secured'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
