# Generated by Django 6.0.1 on 2026-02-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0007_alter_agreement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('offer', 'Offer'), ('system', 'System')], default='text', max_length=10),
        ),
    ]
