# Generated by Django 6.0.3 on 2026-03-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0008_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(choices=[('buy_sell', 'Buy/Sell'), ('service', 'Service'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='fee_payer',
            field=models.CharField(choices=[('me', 'Me'), ('other', 'Other'), ('split', 'Split')], default='split', max_length=10),
        ),
    ]
