# Generated by Django 6.0.3 on 2026-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0010_agreement_pending_seller_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='buyer_debited_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='buyer_debited_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='buyer_fee_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='buyer_total_debited',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='cancelled_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='expired_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='expires_grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='expires_reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='expires_reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='timeline_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='timeline_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementoffer',
            name='timeline_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='agreementoffer',
            name='timeline_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreementoffer',
            name='timeline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
