# Generated by Django 6.0.1 on 2026-01-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO 4217 Currency Code (e.g., USD, GBP)', max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Exchange rate to NGN', max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
