# Generated by Django 6.0.1 on 2026-01-14 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wager',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('Head-2-Head', 'Head-2-Head'), ('Group', 'Group')], max_length=20)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Esports', 'Esports'), ('Politics', 'Politics'), ('Crypto', 'Crypto'), ('Stocks', 'Stocks'), ('Entertainment', 'Entertainment'), ('Games', 'Games'), ('Others', 'Others')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('proofMethod', models.CharField(choices=[('Mutual confirmation', 'Mutual confirmation'), ('Proof upload', 'Proof upload')], max_length=30)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('shareLink', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_wagers', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenged_wagers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
