# Generated by Django 6.0.1 on 2026-01-27 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='wager_messages', to=settings.AUTH_USER_MODEL)),
                ('wager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wager.wager')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
