# Generated by Django 6.0.1 on 2026-01-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('DRAW', 'Draw'), ('MATCHED', 'Matched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
