# Generated by Django 6.0.1 on 2026-01-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0003_alter_wager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='category',
            field=models.CharField(choices=[('Public', 'Public'), ('Sports', 'Sports'), ('Social', 'Social'), ('Skills', 'Skills'), ('Predictions', 'Predictions'), ('Fitness', 'Fitness'), ('Work', 'Work'), ('Learning', 'Learning'), ('Entertainment', 'Entertainment'), ('Gaming', 'Gaming'), ('Tech', 'Tech'), ('Money', 'Money'), ('Community', 'Community'), ('Others', 'Others')], max_length=20),
        ),
    ]
