# Generated by Django 6.0.1 on 2026-01-28 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0004_alter_wager_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='drawRequestedBy',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_draws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wager',
            name='drawStatus',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='none', max_length=20),
        ),
    ]
