# Generated by Django 6.0.1 on 2026-01-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0005_wager_drawrequestedby_wager_drawstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='mode',
            field=models.CharField(choices=[('Group', 'Group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wager',
            name='proofMethod',
            field=models.CharField(choices=[('Mutual confirmation', 'Mutual confirmation')], max_length=30),
        ),
    ]
