# Generated by Django 6.0.1 on 2026-02-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0006_alter_wager_mode_alter_wager_proofmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
    ]
