# Generated by Django 6.0.1 on 2026-02-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0007_wager_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='amount_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='wager',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='wager',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wager',
            name='mode',
            field=models.CharField(choices=[('Head-2-Head', 'Head-2-Head'), ('Group', 'Group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wager',
            name='proofMethod',
            field=models.CharField(choices=[('Mutual confirmation', 'Mutual confirmation'), ('Proof upload', 'Proof upload')], max_length=30),
        ),
    ]
