# Generated by Django 6.0.1 on 2026-02-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0008_wager_amount_ngn_wager_amount_usd_alter_wager_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('DRAW', 'Draw'), ('MATCHED', 'Matched'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
