# Generated by Django 6.0.1 on 2026-02-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0009_alter_wager_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wager',
            old_name='shareLink',
            new_name='share_link',
        ),
    ]
