# Generated by Django 6.0.1 on 2026-02-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
