# Generated by Django 6.0.1 on 2026-02-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_amount_ngn_transaction_amount_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('TRANSACTPAY', 'TransactPay (Naira)'), ('NOWPAYMENTS', 'NOWPayments (Crypto)')], max_length=20, null=True),
        ),
    ]
