# Generated by Django 6.0.1 on 2026-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PAYSTACK', 'Paystack (Naira)'), ('NOWPAYMENTS', 'NOWPayments (Crypto)')], max_length=20, null=True),
        ),
    ]
