# Generated by Django 6.0.1 on 2026-03-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('WAGER_PAYMENT', 'Wager Payment'), ('WAGER_WIN', 'Wager Win'), ('WAGER_REFUND', 'Wager Refund'), ('AGREEMENT_PAYMENT', 'Agreement Payment'), ('AGREEMENT_PAYOUT', 'Agreement Payout')], max_length=20),
        ),
    ]
