# Generated by Django 6.0.3 on 2026-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('WAGER_PAYMENT', 'Wager Payment'), ('WAGER_WIN', 'Wager Win'), ('WAGER_REFUND', 'Wager Refund'), ('AGREEMENT_PAYMENT', 'Agreement Payment'), ('AGREEMENT_PAYOUT', 'Agreement Payout'), ('AGREEMENT_REFUND', 'Agreement Refund')], max_length=20),
        ),
    ]
