"""
Django settings for middleman_api project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import firebase_admin
from firebase_admin import credentials
import requests
import dj_database_url

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^n$tzx$-iumpm+q#5ajp(t1%$*y%*^8o98+5dfdk_^9-syq7h&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
USE_R2 = os.getenv("USE_R2", "False") == "True"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    'corsheaders',

    # Local
    'users',
    'wallet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'middleman_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'middleman_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'wallet_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'wallet.sqlite3',
    }
}

DATABASE_URL = os.getenv('DATABASE_URL')
WALLET_DATABASE_URL = os.getenv('WALLET_DATABASE_URL')

db_from_env = dj_database_url.config(conn_max_age=600, default=DATABASE_URL)
DATABASES['default'].update(db_from_env)

wallet_db_from_env = dj_database_url.config(conn_max_age=600, default=WALLET_DATABASE_URL)
DATABASES['wallet_db'].update(wallet_db_from_env)



DATABASE_ROUTERS = ['middleman_api.db_routers.WalletRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

if USE_R2:
    R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID")
    R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY")
    R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
    R2_ACCOUNT_ID = os.getenv("R2_ACCOUNT_ID")
    R2_REGION = os.getenv("R2_REGION", "auto")

    # Cloudflare R2 S3-compatible endpoint
    AWS_S3_ENDPOINT_URL = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    
    AWS_S3_REGION_NAME = R2_REGION
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_DEFAULT_ACL = None

    AWS_S3_CUSTOM_DOMAIN = "cdn.midman.app"

    # Use R2 storage backends
    STATICFILES_STORAGE = "middleman_api.storage_backends.R2StaticStorage"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"

    DEFAULT_FILE_STORAGE = "middleman_api.storage_backends.R2MediaStorage"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

else:
    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"
    STATIC_ROOT = BASE_DIR / "static-root"
    MEDIA_ROOT = BASE_DIR / "media-root"

    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# Firebase Configuration
FIREBASE_CREDENTIALS_PATH = os.getenv('FIREBASE_CREDENTIALS_PATH')

if FIREBASE_CREDENTIALS_PATH:
    if not firebase_admin._apps:
        try:
            cred = None
            # Check if it's a URL (e.g. Cloudflare R2)
            if FIREBASE_CREDENTIALS_PATH.startswith('http://') or FIREBASE_CREDENTIALS_PATH.startswith('https://'):
                try:
                    response = requests.get(FIREBASE_CREDENTIALS_PATH, timeout=10)
                    response.raise_for_status()
                    cred_dict = response.json()
                    cred = credentials.Certificate(cred_dict)
                except requests.RequestException as e:
                    print(f"Warning: Failed to fetch Firebase credentials from URL: {e}")
            # Check if it's a local file path
            elif os.path.exists(FIREBASE_CREDENTIALS_PATH):
                cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
            else:
                 print(f"Warning: FIREBASE_CREDENTIALS_PATH is set but file not found locally: {FIREBASE_CREDENTIALS_PATH}")

            if cred:
                firebase_admin.initialize_app(cred)
                
        except Exception as e:
            print(f"Warning: Failed to initialize Firebase Admin: {e}")
else:
    # Fallback or warning
    # For development without credentials, we might skip this or initialize default
    # But for now, we assume credentials are provided or handled.
    print("Warning: FIREBASE_CREDENTIALS_PATH not set. Firebase Admin not initialized.")

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True # For development

EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
ANYMAIL = {
    "RESEND_API_KEY": os.environ.get("RESEND_API_KEY"),
}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@midman.app")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "main@midman.app")