"""
Django settings for middleman_api project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import firebase_admin
from firebase_admin import credentials
import requests
import dj_database_url

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-default-dev-key-change-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

USE_R2 = os.getenv("USE_R2", "False") == "True"
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")
COMMISSION_SLP_ACCT = os.getenv("COMMISSION_SLP_ACCT")
NOWPAYMENTS_API_KEY = os.getenv("NOWPAYMENTS_API_KEY")
NOWPAYMENTS_SANDBOX_MODE = os.getenv("NOWPAYMENTS_SANDBOX_MODE", "False") == "True"
NOWPAYMENTS_IPN_SECRET = os.getenv("NOWPAYMENTS_IPN_SECRET")
NOWPAYMENTS_WEBHOOK_URL = os.getenv("NOWPAYMENTS_WEBHOOK_URL", "https://api.midman.app/webhooks/nowpayments/")
FRONTEND_URL = os.getenv("FRONTEND_URL", "https://midman.app")
METAMAP_WEBHOOK_SECRET = os.getenv("METAMAP_WEBHOOK_SECRET")

INTERCOM_ACCESS_TOKEN = os.getenv("INTERCOM_ACCESS_TOKEN")
INTERCOM_IDENTITY_SECRET = os.getenv("INTERCOM_IDENTITY_SECRET")
INTERCOM_WEBHOOK_SECRET = os.getenv("INTERCOM_WEBHOOK_SECRET")
INTERCOM_DISPUTE_TICKET_TYPE_ID = os.getenv("INTERCOM_DISPUTE_TICKET_TYPE_ID")


# Production Security Settings
if not DEBUG:
    # Security Middleware settings
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "True") == "True"
    CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "True") == "True"
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", 31536000))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True") == "True"
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "True") == "True"
    
    # Trust the X-Forwarded-Proto header for SSL (Railway handles SSL termination)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Logging Configuration
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': True,
            },
            'users': {  # Add logger for our users app
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': True,
            },
            'middleman_api': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': True,
            },
        },
    }

# Disable strict security during tests to avoid 301 redirects and cookie issues
import sys
if 'test' in sys.argv:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    'corsheaders',
    'channels',

    # Local
    'users',
    'wallet',
    'wager',
    'agreement',
    'rates',
    'fcm_django',

    # Project Config (for management commands)
    'middleman_api',
]

MIDDLEWARE = [
    'middleman_api.middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# APPEND_SLASH = True

ROOT_URLCONF = 'middleman_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'middleman_api.wsgi.application'
ASGI_APPLICATION = 'middleman_api.asgi.application'

if os.getenv("REDIS_URL"):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.getenv("REDIS_URL")],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'wallet_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'wallet.sqlite3',
    },
    'wager_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'wager.sqlite3',
    },
    'agreement_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'agreement.sqlite3',
    }
}

DATABASE_URL = os.getenv('DATABASE_URL')
WALLET_DATABASE_URL = os.getenv('WALLET_DATABASE_URL')
WAGER_DATABASE_URL = os.getenv('WAGER_DATABASE_URL')
AGREEMENT_DATABASE_URL = os.getenv('AGREEMENT_DATABASE_URL')

# Override with environment variables if present (Production)
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )

if WALLET_DATABASE_URL:
    DATABASES['wallet_db'] = dj_database_url.config(
        env='WALLET_DATABASE_URL',
        default=WALLET_DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )

if WAGER_DATABASE_URL:
    DATABASES['wager_db'] = dj_database_url.config(
        env='WAGER_DATABASE_URL',
        default=WAGER_DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )

if AGREEMENT_DATABASE_URL:
    DATABASES['agreement_db'] = dj_database_url.config(
        env='AGREEMENT_DATABASE_URL',
        default=AGREEMENT_DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )

DATABASE_ROUTERS = [
    'middleman_api.db_routers.AuthRouter',
    'middleman_api.db_routers.WalletRouter',
    'middleman_api.db_routers.WagerRouter',
    'middleman_api.db_routers.AgreementRouter'
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

if USE_R2:
    R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID")
    R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY")
    R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
    R2_ACCOUNT_ID = os.getenv("R2_ACCOUNT_ID")
    R2_REGION = os.getenv("R2_REGION", "auto")

    # Cloudflare R2 S3-compatible endpoint
    AWS_S3_ENDPOINT_URL = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    
    AWS_S3_REGION_NAME = R2_REGION
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_DEFAULT_ACL = None

    AWS_S3_CUSTOM_DOMAIN = "cdn.midman.app"

    # Use R2 storage backends
    STORAGES = {
        "default": {
            "BACKEND": "middleman_api.storage_backends.R2MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "middleman_api.storage_backends.R2StaticStorage",
        },
    }
    
    STATICFILES_STORAGE = "middleman_api.storage_backends.R2StaticStorage"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"

    DEFAULT_FILE_STORAGE = "middleman_api.storage_backends.R2MediaStorage"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"
    STATIC_ROOT = BASE_DIR / "static-root"
    MEDIA_ROOT = BASE_DIR / "media-root"

    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'middleman_api.exceptions.custom_exception_handler',
}

# Firebase Configuration
FIREBASE_CREDENTIALS_PATH = os.getenv('FIREBASE_CREDENTIALS_PATH')

# FCM Django Settings
FCM_DJANGO_SETTINGS = {
    # default: _('FCM Django')
    "APP_VERBOSE_NAME": "FCM Django",
    # true if you want to send only to active devices (fcm_device.active)
    "ONE_DEVICE_PER_USER": False,
    # devices to which notifications cannot be sent,
    # are deleted upon receiving error response from FCM
    # default: False
    "DELETE_INACTIVE_DEVICES": False,
}

if FIREBASE_CREDENTIALS_PATH:
    if not firebase_admin._apps:
        try:
            cred = None
            # Check if it's a URL (e.g. Cloudflare R2)
            if FIREBASE_CREDENTIALS_PATH.startswith('http://') or FIREBASE_CREDENTIALS_PATH.startswith('https://'):
                try:
                    response = requests.get(FIREBASE_CREDENTIALS_PATH, timeout=10)
                    response.raise_for_status()
                    cred_dict = response.json()
                    cred = credentials.Certificate(cred_dict)
                except requests.RequestException as e:
                    print(f"Warning: Failed to fetch Firebase credentials from URL: {e}")
            # Check if it's a local file path
            elif os.path.exists(FIREBASE_CREDENTIALS_PATH):
                cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
            else:
                 print(f"Warning: FIREBASE_CREDENTIALS_PATH is set but file not found locally: {FIREBASE_CREDENTIALS_PATH}")

            if cred:
                firebase_admin.initialize_app(cred)
                
        except Exception as e:
            print(f"Warning: Failed to initialize Firebase Admin: {e}")
else:
    # Fallback or warning
    # For development without credentials, we might skip this or initialize default
    # But for now, we assume credentials are provided or handled.
    print("Warning: FIREBASE_CREDENTIALS_PATH not set. Firebase Admin not initialized.")

# CORS Settings
from corsheaders.defaults import default_headers

CORS_ALLOW_ALL_ORIGINS = True  # Relaxing for development
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-device-uuid',
]

if not CORS_ALLOW_ALL_ORIGINS:
    # In production, we must specify allowed origins
    env_cors = os.getenv("CORS_ALLOWED_ORIGINS")
    if env_cors:
        CORS_ALLOWED_ORIGINS = env_cors.split(",")
    else:
        # Fallback defaults for production
        CORS_ALLOWED_ORIGINS = [
            "https://midman.app",
            "https://api.midman.app",
            "capacitor://localhost",
            "http://localhost",
            "http://localhost:8100",
            "http://localhost:5173",
        ]

CSRF_TRUSTED_ORIGINS = [
    "https://api.midman.app",
    "https://localhost",
    "http://localhost",
    "http://localhost:8100",
    "http://localhost:5173",
    "capacitor://localhost",
    "midman://",
    "https://midman.app"
]

EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
ANYMAIL = {
    "RESEND_API_KEY": os.environ.get("RESEND_API_KEY"),
}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@midman.app")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "main@midman.app")


# ── Wallet / Withdrawal ───────────────────────────────────────────────
# Flat NGN fee deducted from every withdrawal (user receives amount - fee).
WITHDRAWAL_COMMISSION_FEE = 300

# The recipient_code of your platform subaccount on Paystack.
# Get it from: Paystack Dashboard → Settings → Subaccounts
COMMISSION_RECIPIENT_CODE = os.getenv("COMMISSION_RECIPIENT_CODE", "ACCT_vofw24vx1x6kfvs")

# User.id of your internal platform account.
# Escrow fees and withdrawal commissions are credited to this wallet.
# Set to None to skip internal crediting (fees stay in Paystack balance).
PLATFORM_FEE_WALLET_USER_ID = None  # e.g. 1 if your admin user is id=1

# ── Escrow ────────────────────────────────────────────────────────────
# 3.5% escrow fee on every completed agreement.
# Split mode charges each side half (1.75%).
ESCROW_FEE_RATE = '0.035'

# ── Celery ────────────────────────────────────────────────────────────
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
